#!/usr/bin/env bash
# AtomGoal hackathon demo script — run after: docker compose up -d && npm run db:seed && npm run dev
set -euo pipefail

BASE_URL="${DEMO_URL:-http://localhost:3000}"

echo ""
echo "══════════════════════════════════════════════════════════════"
echo "  AtomGoal — Demo walkthrough (hackathon submission)"
echo "  App URL: $BASE_URL"
echo "══════════════════════════════════════════════════════════════"
echo ""
echo "Demo accounts (password: password123)"
echo "  • Employee  employee@demo.com   — approved goals, Q1 check-in"
echo "  • Manager   manager@demo.com    — pending approvals, team view"
echo "  • Admin     admin@demo.com      — users, cycles, reports, audit"
echo "  • Extra     emp2@demo.com       — submitted sheet awaiting approval"
echo "  • Extra     emp3@demo.com       — draft sheet (2 goals, submit demo)"
echo ""
echo "─── 1. Employee journey (~3 min) ─────────────────────────────"
echo "  1. Sign in as employee@demo.com"
echo "  2. Dashboard → note cycle phase badge and quarterly progress"
echo "  3. My Goals → open FY 2025-26 sheet (Approved, Locked)"
echo "  4. Quarterly check-in → log achievement for a goal"
echo "  5. Shared Goals → view org-wide objectives"
echo ""
echo "─── 2. Manager journey (~2 min) ──────────────────────────────"
echo "  1. Sign in as manager@demo.com"
echo "  2. Approvals → open Rohan Verma's submitted sheet → Approve or Rework"
echo "  3. Team → review direct reports and check-in status"
echo "  4. Analytics → department / thrust-area charts"
echo ""
echo "─── 3. Admin journey (~3 min) ─────────────────────────────────"
echo "  1. Sign in as admin@demo.com"
echo "  2. Users / Departments / Thrust areas — master data"
echo "  3. Goal cycles — phase windows (Q1 check-in open in seed)"
echo "  4. Reports → export achievement XLSX"
echo "  5. Audit log → filter by entity; Escalations → open items"
echo "  6. Settings → Teams webhook URL (optional bonus)"
echo ""
echo "─── 4. Automated checks (for judges / CI) ───────────────────"
echo "  npm test                  # unit tests (progress + weightage)"
echo "  npm run test:e2e          # Playwright journeys (13 tests)"
echo "  npm run verify:edge-cases # business rule assertions"
echo "  npm run verify:seed       # demo data integrity"
echo "  npm run build             # production build"
echo ""
echo "─── 5. Bonus features to mention ─────────────────────────────"
echo "  • Azure AD SSO (set AZURE_AD_* + NEXT_PUBLIC_AZURE_AD_ENABLED=true)"
echo "  • Email via Resend + Vercel cron (check-reminders, escalations)"
echo "  • Microsoft Teams webhook on goal submission"
echo ""
echo "Open app: $BASE_URL/login"
echo ""
